Update build-kernel.ymld

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -212,45 +212,45 @@ jobs:
           set -euo pipefail
           mkdir -p kernel_workspace && cd kernel_workspace
       
-          FORMATTED_BRANCH="${{ inputs.android_version }}-${{ env.SERIES }}-${{ env.OS_PATCH }}"
-          REMOTE_URL="https://android.googlesource.com/kernel/common"
+          # FORMATTED_BRANCH="${{ inputs.android_version }}-${{ env.SERIES }}-${{ env.OS_PATCH }}"
+          # REMOTE_URL="https://android.googlesource.com/kernel/common"
       
-          echo "Checking if remote branch exists: $FORMATTED_BRANCH"
-          if ! git ls-remote --exit-code "$REMOTE_URL" "refs/heads/${FORMATTED_BRANCH}" > /dev/null 2>&1; then
-            echo "❌ Branch not found: $FORMATTED_BRANCH"
-            exit 0
-          fi
+          # echo "Checking if remote branch exists: $FORMATTED_BRANCH"
+          # if ! git ls-remote --exit-code "$REMOTE_URL" "refs/heads/${FORMATTED_BRANCH}" > /dev/null 2>&1; then
+          #   echo "❌ Branch not found: $FORMATTED_BRANCH"
+          #   exit 0
+          # fi
       
-          if [ ! -d .repo ]; then
-            echo "Initializing repo with branch $FORMATTED_BRANCH"
-            repo init --depth=1 --partial-clone --clone-filter=blob:none \
-              --no-clone-bundle --no-tags \
-              -u https://android.googlesource.com/kernel/manifest \
-              -b common-${FORMATTED_BRANCH} --repo-rev=v2.16
-          else
-            echo "Using existing .repo cache"
-          fi
+          # if [ ! -d .repo ]; then
+          #   echo "Initializing repo with branch $FORMATTED_BRANCH"
+          #   repo init --depth=1 --partial-clone --clone-filter=blob:none \
+          #     --no-clone-bundle --no-tags \
+          #     -u https://android.googlesource.com/kernel/manifest \
+          #     -b common-${FORMATTED_BRANCH} --repo-rev=v2.16
+          # else
+          #   echo "Using existing .repo cache"
+          # fi
       
-          # Check if deprecated branch should be used
-          if git ls-remote "$REMOTE_URL" "refs/heads/deprecated/${FORMATTED_BRANCH}" | grep -q "deprecated"; then
-            DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
-            echo "Switching to deprecated/${FORMATTED_BRANCH} in manifest"
-            sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" "$DEFAULT_MANIFEST_PATH"
-          fi
+          # # Check if deprecated branch should be used
+          # if git ls-remote "$REMOTE_URL" "refs/heads/deprecated/${FORMATTED_BRANCH}" | grep -q "deprecated"; then
+          #   DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
+          #   echo "Switching to deprecated/${FORMATTED_BRANCH} in manifest"
+          #   sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" "$DEFAULT_MANIFEST_PATH"
+          # fi
       
-          echo "Syncing repo..."
-          repo sync --optimized-fetch -c --no-tags --no-clone-bundle -j$(nproc --all)
+          # echo "Syncing repo..."
+          # repo sync --optimized-fetch -c --no-tags --no-clone-bundle -j$(nproc --all)
 
-          ls -la
-
-          cd common
-          echo "babiusabfbjdk hjsk ih a"
-          ls -la
-          # aria2c -s16 -x16 -k1M https://github.com/aosp-mirror/kernel_common/archive/refs/heads/android15-6.6-2024-08.zip -o common.zip
           # ls -la
-          # unzip -q common.zip
-          # mv "kernel_common-android15-6.6-2024-08" common
-          # rm -rf common.zips
+
+          # cd common
+          # echo "babiusabfbjdk hjsk ih a"
+          # ls -la
+          aria2c -s16 -x16 -k1M https://github.com/aosp-mirror/kernel_common/archive/refs/heads/android15-6.6-2024-08.zip -o common.zip
+          ls -la
+          unzip -q common.zip
+          mv "kernel_common-android15-6.6-2024-08" common
+          rm -rf common.zip
           
           echo "Cleaning old ABI exports..."
           rm -rf ./common/android/abi_gki_protected_exports_* || echo "No protected exports!"
