Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -212,51 +212,39 @@ jobs:
           set -euo pipefail
           mkdir -p kernel_workspace && cd kernel_workspace
       
-          # FORMATTED_BRANCH="${{ inputs.android_version }}-${{ env.SERIES }}-${{ env.OS_PATCH }}"
-          # REMOTE_URL="https://android.googlesource.com/kernel/common"
+          FORMATTED_BRANCH="${{ inputs.android_version }}-${{ env.SERIES }}-${{ env.OS_PATCH }}"
+          REMOTE_URL="https://android.googlesource.com/kernel/common"
       
-          # echo "Checking if remote branch exists: $FORMATTED_BRANCH"
-          # if ! git ls-remote --exit-code "$REMOTE_URL" "refs/heads/${FORMATTED_BRANCH}" > /dev/null 2>&1; then
-          #   echo "❌ Branch not found: $FORMATTED_BRANCH"
-          #   exit 0
-          # fi
+          echo "Checking if remote branch exists: $FORMATTED_BRANCH"
+          if ! git ls-remote --exit-code "$REMOTE_URL" "refs/heads/${FORMATTED_BRANCH}" > /dev/null 2>&1; then
+            echo "❌ Branch not found: $FORMATTED_BRANCH"
+            exit 0
+          fi
       
-          # if [ ! -d .repo ]; then
-          #   echo "Initializing repo with branch $FORMATTED_BRANCH"
-          #   repo init --depth=1 --partial-clone --clone-filter=blob:none \
-          #     --no-clone-bundle --no-tags \
-          #     -u https://android.googlesource.com/kernel/manifest \
-          #     -b common-${FORMATTED_BRANCH} --repo-rev=v2.16
-          # else
-          #   echo "Using existing .repo cache"
-          # fi
+          if [ ! -d .repo ]; then
+            echo "Initializing repo with branch $FORMATTED_BRANCH"
+            repo init --depth=1 --partial-clone --clone-filter=blob:none \
+              --no-clone-bundle --no-tags \
+              -u https://android.googlesource.com/kernel/manifest \
+              -b common-${FORMATTED_BRANCH} --repo-rev=stable
+          else
+            echo "Using existing .repo cache"
+          fi
       
-          # # Check if deprecated branch should be used
-          # if git ls-remote "$REMOTE_URL" "refs/heads/deprecated/${FORMATTED_BRANCH}" | grep -q "deprecated"; then
-          #   DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
-          #   echo "Switching to deprecated/${FORMATTED_BRANCH} in manifest"
-          #   sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" "$DEFAULT_MANIFEST_PATH"
-          # fi
+          # Check if deprecated branch should be used
+          if git ls-remote "$REMOTE_URL" "refs/heads/deprecated/${FORMATTED_BRANCH}" | grep -q "deprecated"; then
+            DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
+            echo "Switching to deprecated/${FORMATTED_BRANCH} in manifest"
+            sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" "$DEFAULT_MANIFEST_PATH"
+          fi
       
-          # echo "Syncing repo..."
-          # repo sync --optimized-fetch -c --no-tags --no-clone-bundle -j$(nproc --all)
+          echo "Syncing repo..."
+          repo sync --optimized-fetch -c --no-tags --no-clone-bundle -j$(nproc --all)
 
-          aria2c -s16 -x16 -k1M https://github.com/aosp-mirror/kernel_common/archive/refs/heads/android15-6.6-2024-08.zip -o common.zip
-          unzip -q common.zip
-          mv "kernel_common-android15-6.6-2024-08" common
-          rm -rf common.zip
-
-          echo "正在克隆llvm-Clang20工具链..."
-          rm -rf clang20
-          mkdir -p clang20
-          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/clang-r547379.zip -o clang.zip
-          unzip -q clang.zip -d clang20
-          rm -rf clang.zip
-          echo "正在克隆构建工具..."
-          rm -rf build-tools
-          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/build-tools.zip -o build-tools.zip
-          unzip -q build-tools.zip
-          rm -rf build-tools.zip
+          ls -la
+          cd common
+          echo "masuk ke folder common"
+          ls -la
           
           echo "Cleaning old ABI exports..."
           rm -rf ./common/android/abi_gki_protected_exports_* || echo "No protected exports!"
@@ -594,18 +582,8 @@ jobs:
             sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' ./build.config.gki.aarch64
             
             export KBUILD_BUILD_TIMESTAMP="Tue Mar 11 12:18:17 UTC 2025"
-            # export PATH="${GITHUB_WORKSPACE}/kernel_workspace/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
+            export PATH="${GITHUB_WORKSPACE}/kernel_workspace/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
             export PATH="/usr/lib/ccache:$PATH"
-
-            export PATH="${GITHUB_WORKSPACE}/kernel_workspace/clang20/bin:$PATH"
-            export PATH="${GITHUB_WORKSPACE}/kernel_workspace/build-tools/bin:$PATH"
-            CLANG_DIR="${GITHUB_WORKSPACE}/kernel_workspace/clang20/bin"
-            CLANG_VERSION="$($CLANG_DIR/clang --version | head -n 1)"
-            LLD_VERSION="$($CLANG_DIR/ld.lld --version | head -n 1)"
-            echo "编译器信息:"
-            echo "Clang版本: $CLANG_VERSION"
-            echo "LLD版本: $LLD_VERSION"
-            pahole_version=$(pahole --version 2>/dev/null | head -n1); [ -z "$pahole_version" ] && echo "pahole版本：未安装" || echo "pahole版本：$pahole_version"
 
             make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2 gki_defconfig || { echo "make defconfig failed"; exit 1; }
             make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2 Image || { echo "make failed"; exit 1; }
